### Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Guardar el token que recibido

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ZhMmI4ZmM3YjkzMjcxM2VjNDg4NDgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDQ0ODQzOSwiZXhwIjoxNzQ0NDU1NjM5fQ.ksd-5Zqhx4-OX838Ez0kAfPoHwl9-GDhoAs-vRKKmh4

### Obtener todos los clientes
GET http://localhost:8080/api/client
Authorization: Bearer {{token}}

### Crear un cliente
POST http://localhost:8080/api/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cliente 1",
  "email": "cliente@example.com",
  "phone": "600123456",
  "cif": "51021707M",
  "address": {
    "street": "Calle Real",
    "number": 99,
    "postal": 28001,
    "city": "Madrid",
    "province": "Madrid"
  }
}

### Obtener cliente por ID
GET http://localhost:8080/api/client/67fa2dfe7ca5a5ab936c0fd4
Authorization: Bearer {{token}}

### Actualizar cliente
PUT http://localhost:8080/api/client/67fa2dfe7ca5a5ab936c0fd4
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cliente Actualizado"
}

### Archivar cliente (soft delete)
DELETE http://localhost:8080/api/client/archive/67fa2dfe7ca5a5ab936c0fd4
Authorization: Bearer {{token}}

### Obtener clientes archivados
GET http://localhost:8080/api/client/archive
Authorization: Bearer {{token}}

### Restaurar cliente archivado
PATCH http://localhost:8080/api/client/restore/67fa2dfe7ca5a5ab936c0fd4
Authorization: Bearer {{token}}

### Eliminar cliente completamente (hard delete)
DELETE http://localhost:8080/api/client/67fa2dfe7ca5a5ab936c0fd4
Authorization: Bearer {{token}}



