### Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123"
}

### Guardar el token que recibido

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjZhODYzOTRjZmZjNDVmZjcxNTgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDAxNzQxNiwiZXhwIjoxNzQ0MDI0NjE2fQ.hLxkxkQV300xFbAtUxw-JrwseTtVjABfC_rHHEIw9gQ

### Obtener todos los clientes
GET http://localhost:8080/api/client
Authorization: Bearer {{token}}

### Crear un cliente
POST http://localhost:8080/api/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cliente 1",
  "email": "cliente@example.com",
  "phone": "600123456",
  "address": {
    "street": "Calle Real",
    "number": 99,
    "postal": 28001,
    "city": "Madrid",
    "province": "Madrid"
  }
}

### Obtener cliente por ID
GET http://localhost:8080/api/client/67f39e8cfa680d78b52bd830
Authorization: Bearer {{token}}

### Actualizar cliente
PUT http://localhost:8080/api/client/67f39e8cfa680d78b52bd830
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cliente Actualizado"
}

### Archivar cliente (soft delete)
DELETE http://localhost:8080/api/client/archive/67f3a08ba57aa840151e8c3c
Authorization: Bearer {{token}}

### Obtener clientes archivados
GET http://localhost:8080/api/client/archive
Authorization: Bearer {{token}}

### Restaurar cliente archivado
PATCH http://localhost:8080/api/client/restore/67f3a08ba57aa840151e8c3c
Authorization: Bearer {{token}}

### Eliminar cliente completamente (hard delete)
DELETE http://localhost:8080/api/client/67f3a08ba57aa840151e8c3c
Authorization: Bearer {{token}}



