@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjZhODYzOTRjZmZjNDVmZjcxNTgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyODYxNywiZXhwIjoxNzQ0MTM1ODE3fQ.De-r4cva0rfh8TLvZfJYKwz3TxuFONEJF70UGbaEBtU

### Crear albarán con personas y materiales
POST http://localhost:8080/api/deliverynote
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "projectId": "67f4114b50437a84658ab057",
  "description": "Instalación completa realizada el viernes",
  "workEntries": [
    {
      "person": "Carlos Fernández",
      "hours": 6
    },
    {
      "person": "Ana García",
      "hours": 4
    }
  ],
  "materialEntries": [
    {
      "name": "Cables",
      "quantity": 80
    },
    {
      "name": "Interruptores",
      "quantity": 15
    }
  ]
}

### Obtener todos los albaranes creados por el usuario
GET http://localhost:8080/api/deliverynote
Authorization: Bearer {{token}}

### Obtener un albarán por ID
GET http://localhost:8080/api/deliverynote/67f54bb31587fd144f61481b
Authorization: Bearer {{token}}


