@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYjZhODYzOTRjZmZjNDVmZjcxNTgiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyODYxNywiZXhwIjoxNzQ0MTM1ODE3fQ.De-r4cva0rfh8TLvZfJYKwz3TxuFONEJF70UGbaEBtU

### Crear albarán con personas y materiales
POST http://localhost:8080/api/deliverynote
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "projectId": "67f551616517559dbe7f7347",
  "description": "Instalación completa realizada el viernes",
  "workEntries": [
    {
      "person": "Carlos Fernández",
      "hours": 6
    },
    {
      "person": "Ana García",
      "hours": 4
    }
  ],
  "materialEntries": [
    {
      "name": "Cables",
      "quantity": 80
    },
    {
      "name": "Interruptores",
      "quantity": 15
    }
  ]
}

### Obtener todos los albaranes creados por el usuario
GET http://localhost:8080/api/deliverynote
Authorization: Bearer {{token}}

### Obtener un albarán por ID
GET http://localhost:8080/api/deliverynote/67f551786517559dbe7f7349
Authorization: Bearer {{token}}

### Descargar PDF del albarán
GET http://localhost:8080/api/deliverynote/pdf/67f551786517559dbe7f7349
Authorization: Bearer {{token}}

### Eliminar albarán (si no está firmado)
DELETE http://localhost:8080/api/deliverynote/67f551786517559dbe7f7349
Authorization: Bearer {{token}}




