### Guardar el token que recibido

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODE3NGYwYjZmYjkxZTNjNjJlNTQ3MmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjM1ODAyOCwiZXhwIjoxNzQ2MzY1MjI4fQ.DSxFLW3qfkffhhpC8QV1f3VeZB0BlTdw0XweLvK5gWY

### Crear proyecto
POST http://localhost:8080/api/project
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Armando MAQUETAS",
  "projectCode": "PRM001",
  "email": "proyecto@mail.com",
  "code": "CODINT01",
  "clientId": "68175291bd7ec9e4d05f7999",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

### Actualizar proyecto
PUT http://localhost:8080/api/project/68174f92453b27fcbac7784c
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Proyecto actualizado",
  "code": "CODINT02"
}

### Obtener todos los proyectos
GET http://localhost:8080/api/project
Authorization: Bearer {{token}}

### Obtener un proyecto específico
GET http://localhost:8080/api/project/one/68174f92453b27fcbac7784c
Authorization: Bearer {{token}}

### Archivar (soft delete) un proyecto
DELETE http://localhost:8080/api/project/archive/68174f92453b27fcbac7784c
Authorization: Bearer {{token}}

### Eliminar (hard delete) un proyecto definitivamente
DELETE http://localhost:8080/api/project/68174f92453b27fcbac7784c
Authorization: Bearer {{token}}

### Obtener todos los proyectos archivados
GET http://localhost:8080/api/project/archive
Authorization: Bearer {{token}}

### Restaurar un proyecto archivado
PATCH http://localhost:8080/api/project/restore/68174f92453b27fcbac7784c
Authorization: Bearer {{token}}
