### Guardar el token que recibido

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ZhNDU0OTZlMWIzNGE2YTVmMmZiOTMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDQ1NTAwMywiZXhwIjoxNzQ0NDYyMjAzfQ.1PVeYLkIPXNSUVCG7QqHo-zF9i8d9a1mr7VTHHmH0Tk

### Crear proyecto
POST http://localhost:8080/api/project
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Armando MAQUETAS",
  "projectCode": "PRM001",
  "email": "proyecto@mail.com",
  "code": "CODINT01",
  "clientId": "67f3a083a57aa840151e8c3a",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

### Actualizar proyecto
PUT http://localhost:8080/api/project/67f3a74e806f5734190ac73c
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Proyecto actualizado",
  "code": "CODINT02"
}

### Obtener todos los proyectos
GET http://localhost:8080/api/project
Authorization: Bearer {{token}}

### Obtener un proyecto específico
GET http://localhost:8080/api/project/one/67f4115850437a84658ab05b
Authorization: Bearer {{token}}

### Archivar (soft delete) un proyecto
DELETE http://localhost:8080/api/project/archive/67f4115850437a84658ab05b
Authorization: Bearer {{token}}

### Eliminar (hard delete) un proyecto definitivamente
DELETE http://localhost:8080/api/project/67f4115850437a84658ab05b
Authorization: Bearer {{token}}

### Obtener todos los proyectos archivados
GET http://localhost:8080/api/project/archive
Authorization: Bearer {{token}}

### Restaurar un proyecto archivado
PATCH http://localhost:8080/api/project/restore/67f4115850437a84658ab05b
Authorization: Bearer {{token}}
